### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by arkon** [requery/sqlite-android#140]
Bintray is getting sunsetted on May 1st, 2021: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by npurushe** [comment]
Thanks! that's unfortunate news will work to publish the library on maven central instead.

**Comment by mikehardy** [comment]
Alternatively, instead of using another 3rd party, it could be that the internet allows this area to be simplified using new functionality

Gradle itself appears to allow addition of git repos https://stackoverflow.com/a/56787382/9910298

...and/or there is jitpack.io which does the same

I find working with Sonatype / Maven OSS repo to be fairly cumbersome personally and I'd avoid it as a maintainer. Sure it works, I do use it, but if jitpack or a direct dependency worked, simpler IMHO.

Outstanding question would be, does it handle the native compilation?

**Comment by mikehardy** [comment]
I tried doing the gradle source reference thing but:
- the compile is pretty slow, it would be nice to not have to do that
- the NDK is huge! I would only need it for this. Plus the version in the build.gradle here is outdated, would be nice to have a more current one at least
- the build does not appear to be gradle 7 compatible, which is a bummer because I *just* finished forward-porting to gradle 7

All of those things are the reasons we use compiled dependencies so I took a different line and got it to work on jitpack: https://jitpack.io/com/github/mikehardy/sqlite-android/3.35.1.1/build.log

I'll PR the differences over here, then all that needs to happen in the future is tagging the builds (or I guess people can use commit hashes off main branch if needed, but tags are more appealing)

**Comment by heybradharris** [comment]
> Thanks! that's unfortunate news will work to publish the library on maven central instead.

Any progress on this? @npurushe

**Comment by mikehardy** [comment]
It's closed because it's resolved, it's on jitpack.io not maven central though, examine updated instructions and everything @heybradharris https://github.com/requery/sqlite-android/#usage

**Comment by heybradharris** [comment]
> It's closed because it's resolved, it's on jitpack.io not maven central though, examine updated instructions and everything @heybradharris https://github.com/requery/sqlite-android/#usage

I did not see that the group name changed to com.github.requery. Thank you for the reply!

**Comment by kierse** [comment]
I realize the project publishes to [jitpack](https://github.com/requery/sqlite-android/pull/145), however, is there any appetite to revisit also publishing to Maven Central? We don't use jitpack on our project given the not quite immutable nature of artifacts, so being accessible somewhere else would be helpful.

**Comment by npurushe** [comment]
Yes this could be possible, will reopen the issue

**Comment by ZacSweers** [comment]
@npurushe would you be up for a PR to add this support? I could structure it like we do in our projects (https://github.com/slackhq/eithernet for example) using this plugin: https://github.com/vanniktech/gradle-maven-publish-plugin

**Comment by npurushe** [comment]
Yes feel free to submit a PR

**Comment by ZacSweers** [comment]
@npurushe My PR was merged but the latest releases are still not published on maven central. Did you change your mind?

**Comment by npurushe** [comment]
I think there are some manual processes for publishing to maven central that need to be started to make this work, sorry about the delay will try to look into this next week

**Comment by plnice** [comment]
Is 3.43.0 published to Maven Central?

**Comment by plnice** [comment]
Is 3.45.0 published to Maven Central?

**Comment by kierse** [comment]
@npurushe it looks like this stalled on some manual processes for publishing to Maven central. Any chance those can be completed so we can pull from Maven instead of Jitpack?

**Comment by TheMrMilchmann** [comment]
FYI: For the past year, I've been maintaining [a fork](https://github.com/Osmerion/sqlite-android), which is published to Maven central.
