### ISSUE TITLE
Begin transaction deferred?

### ISSUE THREAD

**Issue by molikto** [requery/sqlite-android#6]
I'd like to add deferred mode to this library. but currently there is only `EXCLUSIVE` and `IMMEDIATE`. I have no idea but deferred mode appears in SQLiteConnection class, but is not reachable. I don't know if this is done on purpose. 

This is why I asked: 

http://stackoverflow.com/questions/36256862/is-it-ok-to-keep-a-read-transaction-open-for-a-long-time-in-sqlite/36257462?noredirect=1#comment60152117_36257462

**Comment by npurushe** [comment]
In SQLiteSession? Deferred mode is the default in SQLite that's why it gets mapped to just `BEGIN;`. The problem is in SQLiteDatabase like you said only IMMEDIATE/EXCLUSIVE is supported by the beginTransaction* methods. For whatever reason this wasn't exposed by Google. 

To work around it you can not use the transaction helper methods and instead just `execSql` with `BEGIN DEFERRED;` or just `BEGIN;` and then committing by executing `COMMIT`.  But maybe a method `beginTransactionDeferred` in `SQLiteDatabase` would be helpful? That can be added.

**Comment by molikto** [comment]
@npurushe well. The AOSP wrapper is nasty https://github.com/requery/sqlite-android/blob/52670a48c92a10ed3ded067d93fd8b89c8f53c81/sqlite-android/src/main/java/io/requery/android/database/sqlite/SQLiteProgram.java#L47

**Comment by npurushe** [comment]
Ok yes that is unfortunate

**Comment by npurushe** [comment]
This change will add `beginTransactionDeferred`/`beginTransactionWithListenerDeferred`  https://github.com/requery/sqlite-android/commit/3ee1089862cb9980d58fd76be46e22ba93d70d2e

**Comment by npurushe** [comment]
The `3.12.1` build contains this change
