### ISSUE TITLE
Enable FTS5 compile option

### ISSUE THREAD

**Issue by Zolicha** [requery/sqlite-android#94]
Can you add "DSQLITE_ENABLE_FTS5" to the compile flags?

**Comment by mikehardy** [comment]
@Zolicha - if I'm correct this would allow for full text searching and also (why I'm interested) comparisons could then be made with this library between strings while stripping diacritics etc. I believe if this were done it would increase the size of the distribution a lot because there would need to be an internationalization library used as well (a choice of either icu or something else if my read of the sqlite.org docs were correct) and I'm not sure if the platform provides that in a reliable way. Do you have any guidance from your experience how best to alter the makefile and generate a reliable build + what the size change would be?

**Comment by jasonsparc** [comment]
@mikehardy As far as I know, all that is necessary is to enable the `SQLITE_ENABLE_FTS5` flag in the [`sqlite-android/src/main/jni/sqlite/Android.mk`](https://github.com/requery/sqlite-android/blob/master/sqlite-android/src/main/jni/sqlite/Android.mk) file.

At the moment, the official [SQLite Android Bindings](https://www.sqlite.org/android/doc/trunk/www/install.wiki) sets the `SQLITE_ENABLE_FTS5` option on by default, while leaving out the FTS3 and FTS4 extensions.

As for the ICU part, I think you're talking about the ICU tokenizer. I'm not sure what you meant about needing an internationalization library, but you might have confused that from the [docs](https://www.sqlite.org/fts5.html#_changes_to_create_virtual_table_statements_) that says, *the difference between FTS3/4 is that, FTS5 has no ICU tokenizer*. Also, I don't think FTS5 would even need some internationalization library, its tokenizers are the same as that from FTS3/4, only without the ICU tokenizer. Even FTS3/4 already have the porter tokenizer built-in.

Therefore the increase in size (as far as I know), should only be a few kilobytes.
